### ISSUE TITLE
installing the libtwinsvm from source on windows 

### ISSUE THREAD

**Issue by samitnissrine** [mir-am/LIBTwinSVM#6]
after installing all the requirements i get this error that says that both numpy library and cython are not found. any idea to fix the issue????

PS C:\Users\Zbook> pip install LIBTwinSVM
Collecting LIBTwinSVM
  Using cached LIBTwinSVM-0.3.0.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "<string>", line 116, in get_numpy_status
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "<string>", line 142, in get_cython_status
      ModuleNotFoundError: No module named 'cython'
      Traceback (most recent call last):
        File "C:\Users\Zbook\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Zbook\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Zbook\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Zbook\AppData\Local\Temp\pip-build-env-8u8l0hbp\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Zbook\AppData\Local\Temp\pip-build-env-8u8l0hbp\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Zbook\AppData\Local\Temp\pip-build-env-8u8l0hbp\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Zbook\AppData\Local\Temp\pip-build-env-8u8l0hbp\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 322, in <module>
        File "<string>", line 256, in setup_package
        File "<string>", line 177, in check_install_updated
      ImportError: Numerical Python (NumPy) is not installed. LIBTwinSVM requires NumPy >= 1.14.0.
       Please check out the installation guide of the LIBTwinSVM:
      https://libtwinsvm.readthedocs.io/en/latest/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by Alexandra97A** [comment]
I got the same issue. Could anyone guide how to solve this?

**Comment by samitnissrine** [comment]
> I got the same issue. Could anyone guide how to solve this?

i copied the numpy and cython installed files into the same repositary where the library was installed and it worked.

**Comment by Hariniinduri** [comment]
@samitnissrine I tried to copy the numpy and cython installed files into the same folder where the library was installed. Still It's not working. Getting the same error which is mentioned above. Can anyone please help on this?

**Comment by mir-am** [comment]
> @samitnissrine I tried to copy the numpy and cython installed files into the same folder where the library was installed. Still It's not working. Getting the same error which is mentioned above. Can anyone please help on this?

Please install `numpy` and `cython` using the command below: On Windows, you can run this on the command line or PowerShell. 
```
pip install numpy cython
```
Then, try to install LibTwinSVM from source:
```
pip install .
```

See the installation guide [here](https://github.com/mir-am/LIBTwinSVM?tab=readme-ov-file#installation-from-the-source).

**Comment by Hariniinduri** [comment]
@mir-am Thanks for the quick response. I tried to install the library after installing the dependencies itself. still getting the same error. Attached the screenshot for reference.
![image](https://github.com/mir-am/LIBTwinSVM/assets/85923105/9556913e-6f51-4944-ae77-cce9b4d2fa84)

Please let me know what I am missing here.
Thank you

**Comment by mir-am** [comment]
@Hariniinduri. Thanks for reporting the issue. I need to test the installation on my machine to see if I can reproduce the issue on Windows. I will keep you updated about a possible solution here by the end of the week.
